spring.application.name=professor
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

mercadopago.access-token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.plan-id.pro-professor=${MERCADOPAGO_PLAN_ID_PRO_PROFESSOR}

resend.api-key=${RESEND_API_KEY}
resend.from=${RESEND_FROM}

app.frontend-url=${APP_FRONTEND_URL}
app.url=${APP_FRONTEND_URL}