spring.application.name=professor
spring.datasource.url=jdbc:mysql://localhost:3306/saas_professor
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

//JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

//JWT
jwt.secret=chave-super-secreta-com-pelo-menos-32-caracteres
jwt.access-token-expiration=3600000

//Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


//MP
mercadopago.access-token=TEST-5390391782385679-031002-042ad5def21305118ecfb11dd8196113-1077875222
app.frontend-url=http://localhost:3000
mercadopago.plan-id.pro-professor=a3305a4b86264364b6fd027cbaac139f


resend.api-key=re_4o9M3G6n_Ba5BrbBq4JVAYu1NkotZM9KQ
resend.from=onboarding@resend.dev
app.url=http://localhost:3000